!!python/object:argparse.Namespace
attr_power: 0
box: 15
burn_in_frac: 0.8
config: default
cutoff: 1.25
diameter_viz: 0.3
diffusion_loss_weight: 0.0
diffusion_window: 100
dr: 0.01
dt: 0.001
epsilon: 0.2
exp_name: rdf_longconvergence_lr0.01
gaussian_width: 0.1
kbt0: 1.8
lr: 0.01
min_sigma: 0.73
n_dump: 100
n_epochs: 50
n_layers: 3
n_particle: 512
n_replicas: 1
n_width: 128
nn: true
no_pbc: false
nonlinear: ELU
nvt_time: 9.0
poly: true
poly_power: 3.0
rdf_loss_weight: 1
rdf_sample_frac: 1
rep_power: 12
save_intermediate_rdf: false
seed: 123
sigma: 1.0
t_total: 9.0
temp: 0.8
yaml_config: config.yaml
