includes:
- configs/md22/train.yml
train: False
bond_dev_tol: 0.5
max_frac_unstable_threshold: 0.99
temperature: 500.
steps: 2000 # 1 picosecond per epoch
timestep: 0.5
n_replicas: 24
n_dump: 2000
n_epochs: 300 #corresponding to 300 ps
