#TODO: specify different integrator configs for different molecules based on MD22 paper
src: /pscratch/sd/s/sanjeevr #/data/sanjeevr
name: md22
size: 25percent
molecule: ac_Ala3_NHMe
normalize_labels: False
checkpoint_epoch: -1 #which model to start from
model: nequip
l_max: 1
log_dir: /global/cfs/projectdirs/m4319/sanjeevr #/home/sanjeevr/implicit-md
results_dir: 'results_md22_final_l=1_25percent'
model_dir: /pscratch/sd/s/sanjeevr/MODELPATH #/data/sanjeevr/MODELPATH
seed: 123
dr: 0.02
max_rdf_dist: 15
dv: 0.1
angle_range: [0, 180]
exp_name: "FINAL" #"TEST_lmax1_10percent_resumestrategy0.25_learn_continuous"
integrator: NoseHoover
integrator_config: {"ttime": 20., "ptime": 75., "gamma": 0.1, "taut": 20, "taup": 10000, "compressibility_au": 72.84, "pressure_au": 0.000000632268, "fix_com": True} # corresponds to 1 atm (compressibility calculated at 20C and 1 bar from https://www.linkedin.com/pulse/water-bulk-modulus-compressibility-nikhilesh-mukherjee/ )
timestep: 0.5
temperature: 500.
train: True
eval_model: lmax=2
diffusion_loss_weight: 0
stability_criterion: bond_length_deviation
training_observable: rdf
rdf_loss_weight: 1
adf_loss_weight: 0
vacf_loss_weight: 0
energy_force_loss_weight: 1
diffusion_window: 1000
vacf_window: 100
ic_stddev: 0.0
bond_dev_tol: 0.50 #decay this?
max_frac_unstable_threshold: 0.5 #decay this?
min_frac_unstable_threshold: 0.0 #increase this?
eq_steps: 0
steps: 2000 # 1 picosecond per epoch
n_dump: 50
n_dump_vacf: 2
n_replicas: 16
minibatch_size: 40
adjoint: True
only_learn_if_unstable_threshold_reached: True
only_train_on_unstable_replicas: False
allow_off_policy_updates: False
gradient_clipping: True
grad_clip_norm_threshold: 1.0
use_mse_gradient: True
shuffle: True
optimizer: SGD
reset_probability: 0.05
n_epochs: 1000
lr: 0.001
max_times_reduce_lr: 2 
diameter_viz: 0.08
gaussian_width: 0.01

