#TODO: specify different integrator configs for different molecules based on MD22 paper
src: /data/sanjeevr #/pscratch/sd/s/sanjeevr
name: md22
size: 10percent
molecule: ac_Ala3_NHMe
normalize_labels: False
checkpoint_epoch: -1 #which model to start from
model: nequip
l_max: 1
log_dir: /home/sanjeevr/implicit-md #/global/cfs/projectdirs/m4319/sanjeevr
results_dir: 'results_md22'
model_dir: /home/sanjeevr/MDsim/MODELPATH #/pscratch/sd/s/sanjeevr/MODELPATH 
seed: 123
dr: 0.02
max_rdf_dist: 10
dv: 0.1
angle_range: [0, 180]
exp_name: "TEST" #"TEST_lmax1_10percent_resumestrategy0.25_learn_continuous"
integrator: NoseHoover
train: True
eval_model: lmax=2
diffusion_loss_weight: 0
rdf_loss_weight: 1
adf_loss_weight: 0
vacf_loss_weight: 0
energy_force_loss_weight: 1
diffusion_window: 1000
vacf_window: 100
ic_stddev: 0.0
bond_dev_tol: 0.25 #decay this?
max_frac_unstable_threshold: 0.75 #decay this?
min_frac_unstable_threshold: 0.0 #increase this?
eq_steps: 0
steps: 2000 # 1 picosecond per epoch
n_dump: 50
n_dump_vacf: 2
n_replicas: 64
minibatch_size: 32
adjoint: True
only_learn_if_unstable_threshold_reached: False
only_train_on_unstable_replicas: False
allow_off_policy_updates: False
gradient_clipping: True
use_mse_gradient: True
shuffle: True
optimizer: SGD
reset_probability: 0.0
n_epochs: 600
lr: 0.001
max_times_reduce_lr: 2 
diameter_viz: 0.08
gaussian_width: 0.01

