includes:
- configs/water/train.yml
train: False
dr: 0.012
stability_criterion: rdf
imd_tol: 10000.0
max_frac_unstable_threshold: 0.95
integrator: NPT
integrator_config: {"ttime": 20., "ptime": 2000., "gamma": 0.1, "taut": 20, "taup": 2000, "compressibility_au": 72.84, "pressure_au": 0.0025 , "fix_com": True} # corresponds to 1 atm (compressibility calculated at 20C and 1 bar from https://www.linkedin.com/pulse/water-bulk-modulus-compressibility-nikhilesh-mukherjee/ )
eval_model: post_cycle1_pbcfix_NPT_test
results_dir: 'results_water_localneighborhoods'
exp_name: "TEST_pbcfix"
model: gemnet_t
temperature: 300.
eq_steps: 0
n_replicas: 1
n_epochs: 100
# timestep expt params
timestep: 1
n_dump: 100
steps: 1000




