!!python/object:argparse.Namespace
attr_power: 12.0
batch_size: 10
box: 7
burn_in_frac: 0.8
config: default
cutoff: 1.25
diameter_viz: 0.3
diffusion_loss_weight: 0.0
diffusion_window: 1000
dr: 0.01
dt: 0.005
dv: 0.1
epsilon: 1.0
exp_name: TEST_vacf+rdf_aggregategrads_bs10_12_6_potential_prior6_0
gaussian_width: 0.1
kbt0: 1.8
loss_measure_freq: 100
lr: 0.001
min_sigma: 0.73
n_dump: 20
n_epochs: 1
n_layers: 3
n_particle: 256
n_replicas: 1
n_width: 128
nn: false
no_pbc: false
nonlinear: ELU
nvt_time: 1.0
poly: true
poly_power: 3.0
prior_attr_power: 0.0
prior_epsilon: 1.0
prior_rep_power: 6.0
prior_sigma: 1.0
rdf_loss_weight: 1.0
rdf_sample_frac: 1
rep_power: 6.0
restart_probability: 1.0
save_intermediate_rdf: true
seed: 123
sigma: 1.0
t_total: 1.0
temp: 0.81
vacf_loss_weight: 1.0
vacf_window: 100
yaml_config: config.yaml
