default: &DEFAULT

  n_particle: 256 # number of particles
  temp: 1 # temperature in reduced units
  seed: 123 # random seed used to initialize velocities
  kbt0: 1.8 #multiplier for pressure calculation
  box: 7 #box size
  epsilon: 1.0 # LJ epsilon
  sigma: 1.0 # LJ sigma
  dt: 0.005 # time step for integration
  dr: 0.01 #bin size for RDF calculation (non-differentiable version)
  t_total: 5 # total time
  diameter_viz: 0.3 #particle diameter for Ovito visualization
  n_dump: 100 #save frequency of configurations (also frequency of frames used for ground truth RDF calculation)
  burn_in_frac: 0.2 #initial fraction of trajectory to discount when calculating ground truth rdf

  #learnable potential stuff
  n_epochs: 5 #number of outer loop training epochs
  nn: True
  cutoff: 2.5
  gaussian_width: 0.1
  n_width: 128
  n_layers: 3
  nonlinear: 'ELU'



  