!!python/object/apply:types.SimpleNamespace
state:
  adf_loss_weight: 0
  allow_off_policy_updates: false
  amp: false
  angle_range:
  - 0
  - 180
  bond_dev_tol: 0.25
  checkpoint: null
  checkpoint_epoch: -1
  cpu: false
  diameter_viz: 0.08
  diffusion_loss_weight: 0
  diffusion_window: 1000
  distributed: false
  distributed_backend: nccl
  distributed_port: 13356
  dr: 0.02
  dv: 0.1
  energy_loss_weight: 0.05
  eq_steps: 0
  eval_model: post
  exp_name: TEST_resumestrategy0.25_learn_continuous
  force_loss_weight: 0.95
  gaussian_width: 0.01
  gradient_clipping: true
  ic_stddev: 0.0
  identifier: ''
  integrator: NoseHoover
  integrator_config:
    gamma: 0.1
    temperature: 500.0
    timestep: 0.5
    ttime: 20.0
  is_debug: false
  kcal: false
  local_rank: 0
  lr: 0.001
  max_frac_unstable_threshold: 0.01
  max_rdf_dist: 10
  max_times_reduce_lr: 2
  min_frac_unstable_threshold: 0.0
  minibatch_size: 80
  mode: train
  model: schnet
  model_dir: /pscratch/sd/s/sanjeevr/MODELPATH
  molecule: aspirin
  n_dump: 50
  n_epochs: 500
  n_replicas: 128
  name: md17
  no_ift: false
  noddp: false
  normalize_labels: false
  optimizer: SGD
  print_every: 200
  rdf_loss_weight: 1
  restart_probability: 0.0
  results_dir: results_nnip_continuous_new
  run_dir: MODELPATH/
  save_intermediate_rdf: false
  save_name: nnip-ift
  seed: 0
  shuffle: true
  size: 1k
  src: /pscratch/sd/s/sanjeevr
  steps: 2000
  submit: false
  summit: false
  test_batch_size: 1000
  timestamp_id: null
  train: true
  use_mse_gradient: true
  vacf_loss_weight: 0
  vacf_window: 100
  world_size: 1
