!!python/object:argparse.Namespace
box: 7
burn_in_frac: 0.2
config: default
cutoff: 2.5
diameter_viz: 0.3
dr: 0.01
dt: 0.0005
epsilon: 0.2
gaussian_width: 0.1
kbt0: 1.8
min_sigma: 0.5
n_dump: 50
n_epochs: 1
n_layers: 3
n_particle: 1023
n_width: 128
nn: false
nonlinear: ELU
poly: true
poly_power: 3.0
save_intermediate_rdf: true
seed: 123
sigma: 1.0
t_total: 5.0
temp: 1
yaml_config: config.yaml
