!!python/object:argparse.Namespace
box: 15
burn_in_frac: 0.2
config: default
cutoff: 2.5
diameter_viz: 0.3
dr: 0.01
dt: 0.0005
epsilon: 1.0
exp_name: testgsd
gaussian_width: 0.1
inference: false
kbt0: 1.8
n_dump: 10
n_epochs: 1
n_layers: 3
n_particle: 1023
n_width: 128
nn: false
nonlinear: ELU
pretrained_model_dir: ''
save_intermediate_rdf: false
seed: 123
sigma: 1.0
t_total: 10.0
temp: 1.0
yaml_config: config.yaml
