!!python/object:argparse.Namespace
attr_power: 0
box: 7
burn_in_frac: 0.2
config: default
cutoff: 2.5
diameter_viz: 0.3
diffusion_loss_weight: 100
diffusion_window: 100
dr: 0.01
dt: 0.005
epsilon: 1.0
exp_name: ''
gaussian_width: 0.1
kbt0: 1.8
min_sigma: 0.5
n_dump: 10
n_epochs: 1
n_layers: 3
n_particle: 256
n_width: 128
nn: false
no_pbc: false
nonlinear: ELU
num_threads: 1
nvt_time: 5
poly: false
poly_power: -3.0
rdf_loss_weight: 1
rdf_sample_frac: 1
rep_power: 12
save_intermediate_rdf: false
seed: 123
sigma: 1.0
t_total: 5
temp: 1
yaml_config: config.yaml
