trainer: trainer

dataset:
  src: /home/sanjeevr/nnip-rl/data
  name: md17
  size: 10k
  molecule: benzene
  normalize_labels: False
  model: schnet
  model_dir: '/home/sanjeevr/nnip-rl/pretrained_models/'
  schnet_model_dir: '/home/sanjeevr/nnip-rl/pretrained_models/'
  save_name: 'nnip-rl'
  

logger: 
  log_to_wandb: False
  wandb_api_key: f7892f37dd96b5f1da5c85a410300bb661f3c4de
  project: nnip-rl-gail

task:
  r_max_reward: 1.25 #this is for fitting the GMM (Nequip will still use the r_max from the original model config)
  variance_mode: "diag" #fixed, diag, or full
  training_iterations: 100
  reward_mode: 'gail'
  discriminator_name: 'train_discriminator_lrdecay'


#   dataset: lmdb
#   description: "Regressing to energies and forces"
#   type: regression
#   metric: made
#   labels:
#     - potential energy
#   grad_input: atomic forces
#   train_on_free_atoms: True
#   eval_on_free_atoms: True
    
eval:
  evaluation_duration_unit: "episodes"
  env_config: {"mode": "eval"}

ift:
  seed: 123
  kbt0: 1.8
  box: 7
  epsilon: 0.2
  sigma: 1
  prior_epsilon: 1
  prior_sigma: 1
  prior_rep_power: 3
  prior_attr_power: 0
  rep_power: 9
  attr_power: 3
  poly: True
  poly_power: 3.0
  min_sigma: 0.73
  dt: 0.005
  dr: 0.01
  dv: 0.1
  exp_name: "TEST_vacf+rdf_aggregategrads_bs10_9_3_potential_prior3_0"
  diffusion_window: 1000
  vacf_window: 100
  batch_size: 10
  lr: 0.001
  t_total: 15
  nvt_time: 15
  n_replicas: 1
  diameter_viz: 0.3
  n_dump: 20
  burn_in_frac: 0.8
  n_epochs: 100
  diffusion_loss_weight: 0
  vacf_loss_weight: 1
  rdf_loss_weight: 1
  nn: True
  cutoff: 2.5
  gaussian_width: 0.1
  n_width: 128
  n_layers: 3
  nonlinear: 'ELU'
  kcal: False
  T_init: 500.
  integrator: NoseHoover
  integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20.}
  name: md_500ps_discriminatordata_123

  
optim:
  early_stopping_time: 604800
  early_stopping_lr: 0.000001 
  seed: 123
  n_replicas: 1
  vacf_window: 100

simulate:
  


# nequip_data_config: configs/simulate/nequip_data_cfg/aspirin.yml
# identifier: 300ps
# sim_type: ocp
# seed: 123

# steps: 100000
# max_test_points: 1000

