trainer: trainer

dataset:
  src: /home/sanjeevr/nnip-rl/data
  name: md17
  size: 10k
  molecule: aspirin
  normalize_labels: False
  model: schnet
  model_dir: '/home/sanjeevr/nnip-rl/pretrained_models/' #'/home/sanjeevr/MDsim/MODELPATH'  #'/data/ishan-amin/MODELPATH'
  save_name: 'nnip-rl'
  

logger: 
  log_to_wandb: False
  wandb_api_key: f7892f37dd96b5f1da5c85a410300bb661f3c4de
  project: nnip-rl-gail


#   dataset: lmdb
#   description: "Regressing to energies and forces"
#   type: regression
#   metric: made
#   labels:
#     - potential energy
#   grad_input: atomic forces
#   train_on_free_atoms: True
#   eval_on_free_atoms: True
  

ift:
  seed: 123
  kbt0: 1.8
  box: 7
  epsilon: 0.2
  sigma: 1
  prior_epsilon: 1
  prior_sigma: 1
  prior_rep_power: 3
  prior_attr_power: 0
  rep_power: 9
  attr_power: 3
  poly: True
  poly_power: 3.0
  min_sigma: 0.73
  dt: 0.005
  dr: 0.02
  max_rdf_dist: 10
  dv: 0.1
  exp_name: "TEST_mymodel"
  diffusion_window: 1000
  vacf_window: 10
  batch_size: 100
  lr: 0.001
  t_total: 100
  nvt_time: 100
  n_replicas: 1
  diameter_viz: 0.08
  n_dump: 10
  save_intermediate_rdf: False
  burn_in_frac: 0.8
  n_epochs: 1
  diffusion_loss_weight: 0
  vacf_loss_weight: 0
  rdf_loss_weight: 1
  nn: True
  cutoff: 2.5
  restart_probability: 0.0
  loss_measure_freq: 100
  gaussian_width: 0.01
  n_width: 128
  n_layers: 3
  nonlinear: 'ELU'
  kcal: False
  T_init: 500.
  integrator: NoseHoover
  steps: 10
  integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20.} ##ttime is only used for NVT setup - it's not the total time
  name: md_500ps_discriminatordata_123

