trainer: trainer

dataset:
  src: /data/sanjeevr
  name: md17
  size: 1k
  molecule: naphthalene
  normalize_labels: False
  checkpoint_epoch: 10 #which model to start from
  model: schnet
  model_dir: '/data/ishan-amin/MODELPATH/' #'/home/sanjeevr/MDsim/MODELPATH'
  save_name: 'nnip-ift'
  

logger: 
  log_to_wandb: False
  wandb_api_key: f7892f37dd96b5f1da5c85a410300bb661f3c4de
  project: nnip-rl-gail
  
ift:
  seed: 123
  dr: 0.02
  max_rdf_dist: 10
  dv: 0.1
  exp_name: "TEST"
  diffusion_loss_weight: 0
  vacf_loss_weight: 0
  rdf_loss_weight: 1
  diffusion_window: 1000
  vacf_window: 50
  ic_stddev: 0.05
  eq_steps: 100
  steps: 300
  n_dump: 50
  n_replicas: 10
  minibatch_size: 120
  test_batch_size: 1000
  shuffle: True
  restart_probability: 1.0
  n_epochs: 1
  lr: 0.001
  diameter_viz: 0.08
  save_intermediate_rdf: False
  nn: True
  gaussian_width: 0.01
  kcal: False
  integrator: Langevin
  integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20., "gamma": 0.1} ##ttime is only used for NVT setup - it's not the total time
  name: md_500ps_discriminatordata_123

