trainer: trainer

dataset:
  src: /data/sanjeevr
  name: md17
  size: 1k
  molecule: benzene
  normalize_labels: False
  checkpoint_epoch: 10 #which model to start from
  model: schnet
  model_dir: '/data/ishan-amin/MODELPATH/' #'/home/sanjeevr/MDsim/MODELPATH'
  save_name: 'nnip-rl'
  

logger: 
  log_to_wandb: False
  wandb_api_key: f7892f37dd96b5f1da5c85a410300bb661f3c4de
  project: nnip-rl-gail


#   dataset: lmdb
#   description: "Regressing to energies and forces"
#   type: regression
#   metric: made
#   labels:
#     - potential energy
#   grad_input: atomic forces
#   train_on_free_atoms: True
#   eval_on_free_atoms: True
  

ift:
  seed: 123
  dr: 0.02
  max_rdf_dist: 10
  dv: 0.1
  exp_name: "TEST"
  diffusion_window: 1000
  vacf_window: 100
  batch_size: 1
  loss_measure_freq: 10
  steps: 1
  restart_probability: 1.0
  lr: 0.001
  n_replicas: 1
  diameter_viz: 0.08
  n_dump: 10
  save_intermediate_rdf: False
  burn_in_frac: 0.8
  n_epochs: 100
  diffusion_loss_weight: 0
  vacf_loss_weight: 0
  rdf_loss_weight: 1
  nn: True
  gaussian_width: 0.01
  kcal: False
  T_init: 500.
  integrator: NoseHoover
  integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20.} ##ttime is only used for NVT setup - it's not the total time
  name: md_500ps_discriminatordata_123

