# trainer: trainer

# logger: 
#   log_to_wandb: False
#   wandb_api_key: f7892f37dd96b5f1da5c85a410300bb661f3c4de
#   project: nnip-rl-gail
  
src: /data/sanjeevr
name: md17
size: 10k
molecule: aspirin
normalize_labels: False
checkpoint_epoch: 440 #which model to start from
model: nequip
results_dir: 'results_nnip'
model_dir: '/data/ishan-amin/MODELPATH/' #'/home/sanjeevr/MDsim/MODELPATH'
save_name: 'nnip-ift'
seed: 123
dr: 0.02
max_rdf_dist: 10
dv: 0.1
angle_range: [0, 360]
no_ift: False
exp_name: "TEST_nequip"
integrator: NoseHoover
integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20., "gamma": 0.1} ##ttime is only used for NVT setup - it's not the total time
diffusion_loss_weight: 0
vacf_loss_weight: 0
rdf_loss_weight: 1
diffusion_window: 1000
vacf_window: 100
ic_stddev: 0.0
bond_dev_tol: 0.25 #decay this?
max_frac_unstable_threshold: 0.75 #decay this?
min_frac_unstable_threshold: 0.0 #increase this?
eq_steps: 100
steps: 2000 # 1 femtosecond per epoch
n_dump: 50
n_replicas: 128
minibatch_size: 80
allow_off_policy_updates: False
gradient_clipping: True
use_mse_gradient: True
shuffle: True
optimizer: SGD
restart_probability: 0.0
n_epochs: 1000
lr: 0.001
max_times_reduce_lr: 2 
diameter_viz: 0.08
save_intermediate_rdf: False
gaussian_width: 0.01
kcal: False
test_batch_size: 1000

