src: /pscratch/sd/s/sanjeevr/ #data/sanjeevr
name: md22
size: all
molecule: DHA
normalize_labels: False
checkpoint_epoch: -1 #which model to start from
model: nequip
log_dir: /global/cfs/projectdirs/m4319/sanjeevr
results_dir: 'results_nnip_continuous_new'
model_dir: '/pscratch/sd/s/sanjeevr/MODELPATH' #/data/ishan-amin/MODELPATH/'
seed: 123
dr: 0.02
max_rdf_dist: 10
dv: 0.1
angle_range: [0, 180]
no_ift: False
exp_name: "TEST"
integrator: NoseHoover
integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20., "gamma": 0.1}
train: True
eval_model: post
diffusion_loss_weight: 0
rdf_loss_weight: 1
adf_loss_weight: 0
vacf_loss_weight: 0
energy_loss_weight: 0.05
force_loss_weight: 0.95
diffusion_window: 1000
vacf_window: 10
ic_stddev: 0.0
bond_dev_tol: 0.25 #decay this?
max_frac_unstable_threshold: 0.0 #decay this?
min_frac_unstable_threshold: 0.0 #increase this?
eq_steps: 0
steps: 20 # 1 picosecond per epoch
n_dump: 10
n_dump_vacf: 1
n_replicas: 16
minibatch_size: 40
only_train_on_unstable_replicas: False
allow_off_policy_updates: False
gradient_clipping: True
use_mse_gradient: True
shuffle: True
optimizer: SGD
reset_probability: 0.05
n_epochs: 500 #corresponding to 300 ps
lr: 0.001
max_times_reduce_lr: 2 
diameter_viz: 0.08
gaussian_width: 0.01

