includes:
- configs/md17/train.yml
train: False
eval_model: post
bond_dev_tol: 0.5
max_frac_unstable_threshold: 0.9
steps: 2000 # 1 picosecond per epoch
n_replicas: 512 #can do more at inference?
n_epochs: 300 #corresponding to 300 ps