src: /pscratch/sd/s/sanjeevr/ #/data/sanjeevr 
name: md17
size: 10k
molecule: salicylic_acid
normalize_labels: False
checkpoint_epoch: -1 #which model to start from
model: schnet
l_max: 3
log_dir: /global/cfs/projectdirs/m4319/sanjeevr #/home/sanjeevr/implicit-md
results_dir: 'results_md17'
model_dir: /pscratch/sd/s/sanjeevr/MODELPATH #/data/ishan-amin/MODELPATH
seed: 123
dr: 0.02
max_rdf_dist: 10
rdf_peak: 1.0
dv: 0.1
angle_range: [0, 180]
exp_name: "TEST"
integrator: NoseHoover
integrator_config: {"timestep": 0.5, "temperature": 500., "ttime": 20., "gamma": 0.1}
train: True
eval_model: pre
diffusion_loss_weight: 0
rdf_loss_weight: 1
adf_loss_weight: 0
vacf_loss_weight: 0
energy_force_loss_weight: 1
diffusion_window: 1000
vacf_window: 100
ic_stddev: 0.0
bond_dev_tol: 0.25 #decay this?
max_frac_unstable_threshold: 0.75 #decay this?
min_frac_unstable_threshold: 0.0 #increase this?
eq_steps: 0
steps: 2000 # 1 picosecond per epoch
n_dump: 50
n_dump_vacf: 2
n_replicas: 128
minibatch_size: 40
adjoint: True
only_learn_if_unstable_threshold_reached: True
only_train_on_unstable_replicas: False
allow_off_policy_updates: False
gradient_clipping: True
use_mse_gradient: True
shuffle: True
optimizer: SGD
reset_probability: 0.05
n_epochs: 500 #corresponding to 300 ps
lr: 0.001
max_times_reduce_lr: 2 
diameter_viz: 0.08
gaussian_width: 0.01

