!!python/object:argparse.Namespace
attr_power: 0
box: 10
burn_in_frac: 0.9
config: default
cutoff: 1.25
diameter_viz: 0.3
diffusion_loss_weight: 1.0
diffusion_window: 10
dr: 0.01
dt: 0.005
epsilon: 0.2
exp_name: test_parallel
gaussian_width: 0.1
kbt0: 1.8
min_sigma: 0.73
n_dump: 1
n_epochs: 1
n_layers: 3
n_particle: 512
n_width: 128
nn: false
no_pbc: false
nonlinear: ELU
num_threads: 1
nvt_time: 1.0
poly: false
poly_power: 3.0
rdf_loss_weight: 0.0
rdf_sample_frac: 1
rep_power: 12
save_intermediate_rdf: false
seed: 123
sigma: 1.0
t_total: 1.0
temp: 0.8
yaml_config: config.yaml
