model_dir: MODELPATH
test_dataset_src: /home/sanjeevr/MDsim/data/mdsim_data/ala/40k/test
dataset_src: /home/sanjeevr/MDsim/data/mdsim_data/ala/local_minimas
nequip_data_config: configs/simulate/nequip_data_cfg/ala.yml
dp_data_path: /home/sanjeevr/MDsim/data/mdsim_data/ala_dp/40k/test
sim_type: ocp
seed: 0
init_idx: 0
identifier: 5ns
save_freq: 1
steps: 250
max_test_points: 100
plumed: True

kcal: False # legacy. want to remove soon.
T_init: 300.
integrator: Langevin
integrator_config: {"timestep": 2., "temperature_K": 300., "friction": 0.5}
