model_dir: MODELPATH
dataset_src: /home/sanjeevr/MDsim/data/mdsim_data/lips/20k/test
dp_data_path: /home/sanjeevr/MDsim/data/mdsim_data/lips/20k/DP/test
nequip_data_config: configs/simulate/nequip_data_cfg/lips.yml
sim_type: ocp
seed: 123
identifier: 50ps_timestep2
save_freq: 1
steps: 25000
max_test_points: 5000

kcal: False
T_init: 520.
integrator: NoseHoover
integrator_config: {"timestep": 2, "temperature": 520., "ttime": 20.}
