!!python/object:argparse.Namespace
box: 7
burn_in_frac: 0.2
config: default
cutoff: 10.0
diameter_viz: 0.3
dr: 0.01
dt: 0.005
epsilon: 1.0
exp_name: TEST
fixed_point_mode: all
gaussian_width: 0.1
inference: false
kbt0: 1.8
n_dump: 1
n_epochs: 1
n_layers: 3
n_particle: 256
n_width: 128
nn: false
nonlinear: ELU
pretrained_model_dir: ''
save_intermediate_rdf: true
seed: 123
sigma: 1.0
t_total: 5.0
temp: 1.0
yaml_config: config.yaml
