!!python/object:argparse.Namespace
attr_power: 0
box: 15
burn_in_frac: 0.9
config: default
cutoff: 2.5
diameter_viz: 0.3
diffusion_loss_weight: 0.0
diffusion_window: 100
dr: 0.01
dt: 0.001
epsilon: 0.2
exp_name: vectorized_tests_1replica
gaussian_width: 0.1
kbt0: 1.8
lr: 0.01
min_sigma: 0.73
n_dump: 50
n_epochs: 1
n_layers: 3
n_particle: 512
n_replicas: 1
n_width: 128
nn: false
no_pbc: false
nonlinear: ELU
nvt_time: 7.0
poly: true
poly_power: 3.0
rdf_loss_weight: 1.0
rdf_sample_frac: 1
rep_power: 12
save_intermediate_rdf: true
seed: 123
sigma: 1.0
t_total: 7.0
temp: 0.2
yaml_config: config.yaml
